### ISSUE TITLE
add repos of @RaphiHeer

### ISSUE THREAD

**Issue by eddex** [eddex/awesome-hslu#25]
@RaphiHeer
also consider https://github.com/RaphiEliteDevs

**Comment by RaphiHeer** [comment]
I have following repos to offer:

- https://github.com/RaphiHeer/raphiheer.github.io - HS16 WebTec Project
- https://github.com/RaphiHeer/CSA_Robot - HS17 C# in Action Project
- https://github.com/RaphiHeer/WebLab_Exercises - FS18 WebLab Excercises (probably not complete)
- https://github.com/RaphiHeer/EBV_Testat01_VehicleCounter - FS18 EBV (Echtzeit Bildverarbeitung am Tech) Testat 1
- https://github.com/RaphiHeer/EBV_Testat02_AreaDetection - FS18 EBV (Echtzeit Bildverarbeitung am Tech) Testat 2
- https://github.com/RaphiHeer/DBS18_ModulCommentator - FS18 DBS Project with RavenDB
- https://github.com/RaphiHeer/MobPro_MovieApp - FS19 MobPro Ionic Excercise
- https://github.com/RaphiHeer/sprg-summary - FS19 SPRG Summary for the Software Developement Part (slides are in englisch, my summary is in german)

I wouldn't really recommend the weblab project from RaphiEliteDevs, since it did not work that well... I might delete it later.

**Comment by eddex** [comment]
alright, thanks! If you want you can create a pull request. otherwise I'll add them as soon as I find the time.

**Comment by eddex** [comment]
> I wouldn't really recommend the weblab project from RaphiEliteDevs, since it did not work that well... I might delete it later.

note: has been deleted
